#!/usr/bin/env python3
"""Offline, deterministic source extraction/build. Writes only new mHC artifacts."""
import os
import hashlib
import pathlib
import re
import subprocess

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[2]
CACHE = pathlib.Path(os.environ['GLM53_TILELANG_CACHE'])  # tilelang kernel cache dir
SOURCES = {
    '451': 'dab18524c90587c2a6dd6686b3631b2f2bfb98cb0a9f605d02a8f98638f7e77d',
    '337': 'c94d4a9663f8b0b8476fe54e04a1c92882d775dcadf60938e21f21e407687c9a',
    'c341': 'b8e4bb86a390549bbef90e555f555403dbae0b69412a3dde15623dfd21a8e2c7',
}

def source(prefix):
    p = next(CACHE.glob(prefix + '*/device_kernel.cu'))
    s = p.read_text()
    assert hashlib.sha256(p.read_bytes()).hexdigest() == SOURCES[prefix]
    return s

HEADER = r'''// Generated by glm53_mhc_build.py from SHA-pinned TileLang sources.
// Scalar helper subset matches tilelang/src/tl_templates/cuda/{reduce,copy}.h.
// No fast-math. Do not change Sinkhorn arithmetic, the 19-loop, or BF16 cuts.
#include <cuda_bf16.h>
#include <cuda_fp8.h>
#include <math_constants.h>
#include <stdint.h>
using uchar = unsigned char;
using bfloat16_t = __nv_bfloat16;
namespace tl {
__device__ __forceinline__ int get_lane_idx() { return threadIdx.x & 31; }
__device__ __forceinline__ int get_warp_idx() { return threadIdx.x >> 5; }
__device__ __forceinline__ void __sync_thread_partial(int id, int count) {
  asm volatile("bar.sync %0, %1;" :: "r"(id), "r"(count) : "memory");
}
template<int N> struct NamedBarrier {
  template<int P> __device__ __forceinline__ static void sync() { __sync_thread_partial(P,N); }
};
struct SumOp { __device__ __forceinline__ float operator()(float a,float b) {return a+b;} };
struct MaxOp { __device__ __forceinline__ float operator()(float a,float b) {return fmaxf(a,b);} };
template<class Op,int N,int Stride,int Offset,class Barrier> struct AllReduce {
  __device__ __forceinline__ static float run(float x,float* buf=nullptr) {
    constexpr int off=N/2;
    if constexpr(off>=32) {
      Barrier::template sync<1>(); buf[threadIdx.x-Offset]=x;
      Barrier::template sync<2>(); x=Op()(x,buf[(threadIdx.x-Offset)^off]);
    } else {x=Op()(x,__shfl_xor_sync(0xffffffff,x,off));}
    if constexpr(off==Stride) return x;
    else return AllReduce<Op,N/2,Stride,Offset,Barrier>::run(x,buf);
  }
};
__device__ __forceinline__ float warp_reduce_sum(float x) {
#pragma unroll
  for(int off=16;off;off>>=1) x=x+__shfl_xor_sync(0xffffffff,x,off);
  return x;
}
__device__ __forceinline__ void cp_async_commit() {asm volatile("cp.async.commit_group;" ::: "memory");}
template<int N> __device__ __forceinline__ void cp_async_wait() {
  if constexpr(N==0) asm volatile("cp.async.wait_all;" ::: "memory");
  else asm volatile("cp.async.wait_group %0;" :: "n"(N) : "memory");
}
template<int N> __device__ __forceinline__ void cp_async_gs(const void* s,const void* g) {
  static_assert(N==16);
  unsigned a=__cvta_generic_to_shared(s);
  asm volatile("cp.async.cg.shared.global [%0], [%1], 16;" :: "r"(a),"l"(g) : "memory");
}
}
// 64 epilogue threads each own eight consecutive BF16 values. A 16-lane
// subwarp covers one 128-value quant group. Use the rounded BF16 values,
// not ol_1 FP32, and match non-UE8M0 module_233/module_333 quant semantics.
__device__ __forceinline__ void mhc_quant8(const bfloat16_t* v, int64_t offset,
                                         uchar* q, float* sf, int layout, int sfp) {
  if(!layout) return; // 0=BF16 only, 1=col-major pitch sfp, 2=row-major pitch32.
  float a=0.f;
#pragma unroll
  for(int j=0;j<8;++j) a=fmaxf(a,fabsf(float(v[j])));
#pragma unroll
  for(int d=8;d;d>>=1) a=fmaxf(a,__shfl_xor_sync(0xffffffff,a,d,16));
  a=fmaxf(a,1e-10f);
  float scale=a*(1.f/448.f), inv=448.f/a;
  int row=offset/4096, group=(offset%4096)/128;
  if((threadIdx.x&15)==0) sf[layout==1 ? group*sfp+row : row*32+group]=scale;
#pragma unroll
  for(int j=0;j<8;++j) q[offset+j]=__nv_cvt_float_to_fp8(fminf(float(v[j])*inv,448.f),__NV_SATFINITE,__NV_E4M3);
}
'''

def body(s):
    start=s.index(' {',s.index('__launch_bounds__'))+2
    return s[start:s.rfind('}')]

def generate():
    s64,s8,sf=source('451'),source('337'),source('c341')
    assert s64.replace('< 64; ++i_split','< 8; ++i_split')==s8
    b=body(s64)
    b=b.replace('< 64; ++i_split','< NS; ++i_split')
    b=b.replace('cudaGridDependencySynchronize();', '')
    b=b.replace('cudaTriggerProgrammaticLaunchCompletion();', '')
    # IDs1/2/3 belong to the 64-thread norm; ID0 belongs to the full CTA.
    assert b.count('__syncthreads();')==1
    b=b.replace('__syncthreads();','tl::__sync_thread_partial(4,96);')
    pat=r'(\*\(uint4\*\)\(layer_input \+ (.*?)\) = \*\(uint4\*\)\((layer_input_local_cast_\d+) \+ 0\);)'
    b,n=re.subn(pat,lambda m:m[1]+'\n        mhc_quant8('+m[3]+', '+m[2]+', q, sf, layout, SFP);',b)
    assert n==3,n
    signature='float* comb_mix, const float* gemm_out_mul, const float* gemm_out_sqrsum, const float* hc_base, const float* hc_scale, bfloat16_t* layer_input, const bfloat16_t* norm_weight, float* post_mix, const bfloat16_t* residual, int num_tokens, uchar* q, float* sf, int layout'
    code=HEADER+'\n// Source hashes: '+repr(SOURCES)+'\n'
    code+='template<int NS, int SFP> __device__ __forceinline__ void mhc_fuse_body('+signature+') {'+b+'}\n'
    # Decode keeps pitch-16 entries; the MTP round (rows<=32) gets pitch-32.
    for ns,suffix,sfp in [(8,'',16),(64,'',16),(64,'_r32',32)]:
        code+=f'extern "C" __global__ __launch_bounds__(96) void glm53_mhc_fuse{ns}_q{suffix}('+signature+') {\n'
        code+='cudaGridDependencySynchronize();\n'
        code+=f'mhc_fuse_body<{ns},{sfp}>(comb_mix,gemm_out_mul,gemm_out_sqrsum,hc_base,hc_scale,layer_input,norm_weight,post_mix,residual,num_tokens,q,sf,layout);\n'
        code+='__syncthreads(); cudaTriggerProgrammaticLaunchCompletion();\n}\n'
    fb=body(sf).replace('cudaGridDependencySynchronize();', '').replace('cudaTriggerProgrammaticLaunchCompletion();', '')
    # The source is intact except the fn load conversion for BF16 storage.
    fb=fb.replace('(pre_fn[', '(float(pre_fn[').replace(')] * cur_residual_values', ')]) * cur_residual_values')
    f_sig='bfloat16_t* cur_residual_out, const bfloat16_t* hidden_in, float* mixes_partial_out, const F* pre_fn, const float* prev_comb_mix, const float* prev_post_mix, const bfloat16_t* prev_residual, float* sqrsum_partial_out, int num_tokens, int split_k'
    code+='template<class F> __device__ __forceinline__ void mhc_fma_body('+f_sig+') {'+fb+'}\n'
    # The MTP round (rows<=32, fn binds are FP32) gets a pitch-32 boundary.
    for typ,suffix,sfp in [('float','f32',16),('bfloat16_t','bf16',16),('float','f32_r32',32)]:
        sig=f_sig.replace('const F*',f'const {typ}*').replace(', int split_k', '')
        sig+=', const float* hc_base, const float* hc_scale, const bfloat16_t* norm_weight, float* comb_mix, float* post_mix, bfloat16_t* layer_input, uchar* q, float* sf, unsigned* counters, int layout'
        code+=f'extern "C" __global__ __launch_bounds__(256) void glm53_mhc_boundary_{suffix}('+sig+') {\n'
        wrap=r'''
  cudaGridDependencySynchronize();
  mhc_fma_body(cur_residual_out,hidden_in,mixes_partial_out,pre_fn,prev_comb_mix,prev_post_mix,prev_residual,sqrsum_partial_out,num_tokens,8);
  // Publish every thread's writes before the leader joins the acq_rel chain.
  // This is a completion counter, not a barrier: non-last CTAs EXIT.
  __threadfence(); __syncthreads();
  __shared__ unsigned last;
  if(threadIdx.x==0) {
    unsigned old;
    asm volatile("atom.acq_rel.gpu.global.add.u32 %0, [%1], 1;" : "=r"(old) : "l"(counters+blockIdx.x) : "memory");
    last=(old==95);
  }
  __syncthreads();
  if(last) {
    if(threadIdx.x<96) mhc_fuse_body<8>(comb_mix,mixes_partial_out,sqrsum_partial_out,hc_base,hc_scale,layer_input,norm_weight,post_mix,cur_residual_out,num_tokens,q,sf,layout);
    __syncthreads();
    // Reset once per row for graph replay. No host memset in the hot path.
    if(threadIdx.x==0) {
      asm volatile("st.release.gpu.global.u32 [%0], 0;" :: "l"(counters+blockIdx.x) : "memory");
    }
  }
  __syncthreads();
  cudaTriggerProgrammaticLaunchCompletion();
}
'''
        code+=wrap.replace('mhc_fuse_body<8>(',f'mhc_fuse_body<8,{sfp}>(')
    (HERE/'glm53_mhc_v2.cu').write_text(code)

def main():
    generate()
    dst=ROOT/'kernels-glm53-handwritten/glm53_mhc_v2.cubin'
    cmd=['/usr/local/cuda-13.0/bin/nvcc','-cubin','-arch=sm_90a','-std=c++17','-O3','-ccbin','/usr/bin/g++-14','--ptxas-options=-v,--register-usage-level=10',str(HERE/'glm53_mhc_v2.cu'),'-o',str(dst)]
    subprocess.run(cmd,check=True)
    print('SHA256',hashlib.sha256(dst.read_bytes()).hexdigest(),str(dst))
if __name__=='__main__': main()
