[package]
name = "dsv41-ar-trace"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
anyhow = "1"
serde_json = "1"
kern-runtime = { path = "../../../../crates/kern-runtime" }
kern-manifest = { path = "../../../../crates/kern-manifest" }
kern-run = { path = "../../../../crates/kern-run" }
