[package]
name = "kern-run"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "kern"

[dependencies]
kern-manifest.workspace = true
kern-pool.workspace = true
kern-runtime.workspace = true
kern-test.workspace = true

anyhow.workspace = true
clap.workspace = true
hex.workspace = true
memmap2.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokenizers.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
